version: "3.8"

services:
  web:
    build: .
    container_name: tuto-apache-php
    ports:
      - "8080:80"
    volumes:
      # Monta tu código local en el directorio web del contenedor
      - ./src:/var/www/html
      # Monta configuración personalizada de Apache
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped
    depends_on:
      - db

  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: tuto-mysql
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tuto
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      # Persistir datos de la base de datos
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  # phpMyAdmin para administrar la base de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tuto-phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: user
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mysql_data:
